version: # 版本号
  major: 12
  minor: 2
  build: 0
serial: damiao # 机器人序列号（用于机器人与配置文件匹配）
description: bus config # 该文件的用途描述。
communication_cycle: 5000000 # 通信周期（单位为ns 纳秒）
type: ethercat   # 通信总线类型：ethercat,general
busdata:
  bus_pdo: # 总线pdo映射列表 (当type 为ethercat时必须配置)
    device_description: /home/robot/Work/EtherCAT/igh/eni/eni.xml #设置信息描描述
    state: Status word # 状态字
    control: Control word # 控制字
    mode: Modes of operation # 模式字
    ac_mode: Modes of operation displa # 实际模式字
    ac_position: Position actual value # 实际位置
    ac_velocity: Velocity actual value # 实际速度
    ac_torque: Torque actual value # 实际力矩
    ac_position2: NULL # 第2路实际位置
    ac_velocity2: NULL # 第2路实际速度
    ac_sensor_torque: NULL # 实际关节力矩传感器
    error_code: NULL # 错误代码
    following_error: NULL # 跟踪误差
    position: Profile target position # 目标位置
    velocity: Target Velocity # 目标速度
    torque: Target torque # 目标力矩
    velocity_offset: Velocity offset # 速度前馈
    torque_offset: Torque offset # 力矩前馈
    torque_max_limit: NULL # 最大力矩限制
    torque_min_limit: NULL # 最小力矩限制
    usr_di: NULL # 用户数字量输入
    usr_do: NULL # 用户数字量输出
    usr_ai: NULL # 用户模拟量输入
    usr_ao: NULL # 用户模拟量输出
    inter_di: NULL # 内部数字量输入
    inter_do: NULL # 内部数字量输出
  general_data: # 通用总线设置 (当type 为general时必须配置)
    device_description: NULL #设置信息描描述
